In [3]:
import pandas as pd

In [2]:
df_ban_75 = pd.read_csv("../data/BAN/adresses-75.csv", sep=";")
df_ban_75.head()

,id,id_fantoir,numero,rep,nom_voie,code_postal,code_insee,nom_commune,code_insee_ancienne_commune,nom_ancienne_commune,...,lat,type_position,alias,nom_ld,libelle_acheminement,nom_afnor,source_position,source_nom_voie,certification_commune,cad_parcelles
0,75101_cfq3tf_00001,NaN,1,NaN,Avenue du Général Lemonnier,75001,75101,Paris 1er Arrondissement,NaN,NaN,...,48.861299,parcelle,NaN,NaN,PARIS,AVENUE DU GENERAL LEMONNIER,commune,commune,1,NaN
1,75101_cfq3tf_00002,NaN,2,NaN,Avenue du Général Lemonnier,75001,75101,Paris 1er Arrondissement,NaN,NaN,...,48.861059,parcelle,NaN,NaN,PARIS,AVENUE DU GENERAL LEMONNIER,commune,commune,1,NaN
2,75101_cfq3tf_00003,NaN,3,NaN,Avenue du Général Lemonnier,75001,75101,Paris 1er Arrondissement,NaN,NaN,...,48.861516,parcelle,NaN,NaN,PARIS,AVENUE DU GENERAL LEMONNIER,commune,commune,1,NaN
3,75101_cfq3tf_00004,NaN,4,NaN,Avenue du Général Lemonnier,75001,75101,Paris 1er Arrondissement,NaN,NaN,...,48.861247,parcelle,NaN,NaN,PARIS,AVENUE DU GENERAL LEMONNIER,commune,commune,1,NaN
4,75101_cfq3tf_00005,NaN,5,NaN,Avenue du Général Lemonnier,75001,75101,Paris 1er Arrondissement,NaN,NaN,...,48.861733,parcelle,NaN,NaN,PARIS,AVENUE DU GENERAL LEMONNIER,commune,commune,1,NaN

In [3]:
df_ban_75.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152331 entries, 0 to 152330
Data columns (total 23 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           152331 non-null  object
 1   id_fantoir                   150637 non-null  object
 2   numero                       152331 non-null  int64
 3   rep                          13878 non-null   object
 4   nom_voie                     152331 non-null  object
 5   code_postal                  152331 non-null  int64
 6   code_insee                   152331 non-null  int64
 7   nom_commune                  152331 non-null  object
 8   code_insee_ancienne_commune  0 non-null       float64
 9   nom_ancienne_commune         0 non-null       float64
 10  x                            152331 non-null  float64
 11  y                            152331 non-null  float64
 12  lon                          152331 non-null  float64
 13  lat                          152331 non-null  float64
 14  type_position                152331 non-null  object
 15  alias                        0 non-null       float64
 16  nom_ld                       0 non-null       float64
 17  libelle_acheminement         152331 non-null  object
 18  nom_afnor                    152331 non-null  object
 19  source_position              152331 non-null  object
 20  source_nom_voie              152331 non-null  object
 21  certification_commune        152331 non-null  int64
 22  cad_parcelles                0 non-null       float64
dtypes: float64(9), int64(4), object(10)
memory usage: 26.7+ MB

In [4]:
df_conso = pd.read_csv("../data/edenis/consommation-annuelle-residentielle-par-adresse.csv", sep=";", low_memory=False)
df_conso.head()

,Année,Code IRIS,Nom IRIS,Numéro de voie,Indice de répétition,Type de voie,Libellé de voie,Code Commune,Nom Commune,Segment de client,Nombre de logements,Consommation annuelle totale de l'adresse (MWh),Consommation annuelle moyenne par logement de l'adresse (MWh),Consommation annuelle moyenne de la commune (MWh),Adresse,Code EPCI,Code Département,Code Région,Tri des adresses
0,2018,920040601,Renoir i,8.0,NaN,ALLEE,VISCONTI,92004,ASNIERES-SUR-SEINE,RESIDENTIEL,10,18.925,1.893,3.346,8 ALLEE VISCONTI,200054781,92.0,11.0,420021
1,2018,920040601,Renoir i,7.0,NaN,ALLEE,VISCONTI,92004,ASNIERES-SUR-SEINE,RESIDENTIEL,10,19.579,1.958,3.346,7 ALLEE VISCONTI,200054781,92.0,11.0,420022
2,2018,920040601,Renoir i,6.0,NaN,ALLEE,VISCONTI,92004,ASNIERES-SUR-SEINE,RESIDENTIEL,10,18.886,1.889,3.346,6 ALLEE VISCONTI,200054781,92.0,11.0,420023
3,2018,920040604,Metro,184.0,NaN,BOULEVARD,VOLTAIRE,92004,ASNIERES-SUR-SEINE,RESIDENTIEL,29,35.316,1.218,3.346,184 BOULEVARD VOLTAIRE,200054781,92.0,11.0,420036
4,2018,920040604,Metro,154.0,NaN,BOULEVARD,VOLTAIRE,92004,ASNIERES-SUR-SEINE,RESIDENTIEL,12,28.286,2.357,3.346,154 BOULEVARD VOLTAIRE,200054781,92.0,11.0,420043

In [10]:
df_conso_paris = df_conso[df_conso["Nom Commune"].str.upper() == "PARIS"]

In [11]:
df_conso_paris

,Année,Code IRIS,Nom IRIS,Numéro de voie,Indice de répétition,Type de voie,Libellé de voie,Code Commune,Nom Commune,Segment de client,Nombre de logements,Consommation annuelle totale de l'adresse (MWh),Consommation annuelle moyenne par logement de l'adresse (MWh),Consommation annuelle moyenne de la commune (MWh),Adresse,Code EPCI,Code Département,Code Région,Tri des adresses
25545,2019,751187206,Chapelle 6,2.0,NaN,PLACE,PIERRE MAC ORLAN,75056,Paris,RESIDENTIEL,41,261.867,6.387,2.941,2 PLACE PIERRE MAC ORLAN,200054781,75.0,11.0,280004
25546,2019,751207802,Saint-Fargeau 2,2.0,NaN,RUE,PIERRE MOUILLARD,75056,Paris,RESIDENTIEL,13,38.163,2.936,2.941,2 RUE PIERRE MOUILLARD,200054781,75.0,11.0,280011
25547,2019,751051903,Val de Grace 3,44.0,NaN,RUE,PIERRE NICOLE,75056,Paris,RESIDENTIEL,10,24.105,2.410,2.941,44 RUE PIERRE NICOLE,200054781,75.0,11.0,280012
25548,2019,751051903,Val de Grace 3,42.0,NaN,RUE,PIERRE NICOLE,75056,Paris,RESIDENTIEL,17,47.702,2.806,2.941,42 RUE PIERRE NICOLE,200054781,75.0,11.0,280013
25549,2019,751051903,Val de Grace 3,41.0,NaN,RUE,PIERRE NICOLE,75056,Paris,RESIDENTIEL,16,53.429,3.339,2.941,41 RUE PIERRE NICOLE,200054781,75.0,11.0,280014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767075,2021,751207813,Saint-Fargeau 13,20.0,NaN,RUE,DU TELEGRAPHE,75056,Paris,RESIDENTIEL,19,149.484,7.868,3.013,20 RUE DU TELEGRAPHE,200054781,75.0,11.0,270055
2767076,2021,751031002,Enfants Rouges 2,7.0,NaN,BOULEVARD,DU TEMPLE,75056,Paris,RESIDENTIEL,14,57.780,4.127,3.013,7 BOULEVARD DU TEMPLE,200054781,75.0,11.0,270064
2767077,2021,751114106,Folie Méricourt 6,36.0,NaN,BOULEVARD,DU TEMPLE,75056,Paris,RESIDENTIEL,25,70.260,2.810,3.013,36 BOULEVARD DU TEMPLE,200054781,75.0,11.0,270073
2767078,2021,751114106,Folie Méricourt 6,12.0,NaN,BOULEVARD,DU TEMPLE,75056,Paris,RESIDENTIEL,22,94.773,4.308,3.013,12 BOULEVARD DU TEMPLE,200054781,75.0,11.0,270084
2767079,2021,751041301,Saint-Merri 1,56.0,NaN,RUE,DU TEMPLE,75056,Paris,RESIDENTIEL,19,73.775,3.883,3.013,56 RUE DU TEMPLE,200054781,75.0,11.0,270102

In [12]:
df_conso_paris.to_csv("../data/edenis/consommation-annuelle-residentielle-par-adresse-Paris.csv", index=False, encoding='utf-8')

In [5]:
df_conso.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2821929 entries, 0 to 2821928
Data columns (total 19 columns):
 #   Column                                                         Non-Null Count    Dtype
---  ------                                                         --------------    -----
 0   Année                                                          2821929 non-null  int64
 1   Code IRIS                                                      2821929 non-null  object
 2   Nom IRIS                                                       2821929 non-null  object
 3   Numéro de voie                                                 2821922 non-null  float64
 4   Indice de répétition                                           154203 non-null   object
 5   Type de voie                                                   2810900 non-null  object
 6   Libellé de voie                                                2821929 non-null  object
 7   Code Commune                                                   2821929 non-null  int64
 8   Nom Commune                                                    2821871 non-null  object
 9   Segment de client                                              2821929 non-null  object
 10  Nombre de logements                                            2821929 non-null  int64
 11  Consommation annuelle totale de l'adresse (MWh)                2821929 non-null  float64
 12  Consommation annuelle moyenne par logement de l'adresse (MWh)  2821929 non-null  float64
 13  Consommation annuelle moyenne de la commune (MWh)              2821929 non-null  float64
 14  Adresse                                                        2821929 non-null  object
 15  Code EPCI                                                      2820947 non-null  object
 16  Code Département                                               2820947 non-null  float64
 17  Code Région                                                    2820947 non-null  float64
 18  Tri des adresses                                               2821929 non-null  int64
dtypes: float64(6), int64(4), object(9)
memory usage: 409.1+ MB

In [6]:
df_dpe_75 = pd.read_csv("../data/dpe/dpe_paris_full.csv", nrows=5000, low_memory=False)
df_dpe_75.head(10)

,configuration_installation_chauffage_n1,conso_chauffage_installation_chauffage_n1,type_generateur_n1_ecs_n1,numero_voie_ban,score_ban,surface_habitable_immeuble,conso_auxiliaires_ep,deperditions_murs,cout_eclairage,conso_auxiliaires_ef,...,conso_chauffage_generateur_n2_installation_n2,surface_totale_capteurs_pv,nombre_module,facteur_couverture_solaire_installation_chauffage_n1,facteur_couverture_solaire_saisi_n1,facteur_couverture_solaire_saisi_installation_chauffage_n1,provenance_id_rnb,id_rnb,description_generateur_n2_ecs_n1,numero_rpls_logement
0,Installation de chauffage simple,3506.6,Réseau de chaleur isolé,50,0.66,23551.0,932.1,14.2,17.6,405.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Installation de chauffage simple,6044.4,Chaudière gaz à condensation 2001-2015,74,0.80,NaN,506.3,35.5,21.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Installation de chauffage simple,17567.8,Chaudière gaz classique avant 1981,29,0.68,NaN,464.6,62.5,71.8,202.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Installation de chauffage simple,3838.1,Chaudière gaz standard 1991-2000,53t,0.65,4840.0,602.7,25.8,24.1,262.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Installation de chauffage simple,40734.6,Chaudière gaz à condensation 2001-2015,37,0.67,NaN,1322.6,240.7,100.3,575.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Installation de chauffage simple,1440.5,Ballon électrique à accumulation vertical Caté...,10,0.88,507.0,480.9,13.0,6.0,209.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Installation de chauffage simple,2514.8,Ballon électrique à accumulation vertical Autr...,5,0.61,NaN,653.4,7.3,15.9,284.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Installation de chauffage simple,2814.2,Ballon électrique à accumulation vertical Caté...,4,0.88,NaN,214.4,24.7,6.0,93.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Installation de chauffage simple,3754.3,Ballon électrique à accumulation vertical Caté...,103,0.80,3171.5,277.3,2302.5,27.7,120.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Installation de chauffage simple,24025.5,Chaudière gaz standard 2001-2015,25,0.68,NaN,771.5,113.8,72.0,335.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_dpe_75.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Columns: 225 entries, configuration_installation_chauffage_n1 to numero_rpls_logement
dtypes: float64(127), int64(8), object(90)
memory usage: 8.6+ MB

In [16]:
df_dpe_75.shape

(5000, 225)

In [13]:
list(df_dpe_75.columns)

['configuration_installation_chauffage_n1',
 'conso_chauffage_installation_chauffage_n1',
 'type_generateur_n1_ecs_n1',
 'numero_voie_ban',
 'score_ban',
 'surface_habitable_immeuble',
 'conso_auxiliaires_ep',
 'deperditions_murs',
 'cout_eclairage',
 'conso_auxiliaires_ef',
 'statut_geocodage',
 'ventilation_posterieure_2012',
 'cout_chauffage',
 'conso_5_usages_par_m2_ep',
 'date_etablissement_dpe',
 'conso_ecs_ef_energie_n1',
 'conso_ecs_ef_energie_n2',
 'emission_ges_chauffage',
 'description_installation_chauffage_n1',
 'conso_5_usages_par_m2_ef',
 'cout_ecs_energie_n2',
 'conso_chauffage_ef_energie_n1',
 'conso_chauffage_ef_energie_n2',
 'qualite_isolation_menuiseries',
 'cout_total_5_usages_energie_n2',
 'date_reception_dpe',
 'cout_total_5_usages_energie_n1',
 'cout_ecs_energie_n1',
 'qualite_isolation_plancher_bas',
 'modele_dpe',
 'qualite_isolation_enveloppe',
 'conso_chauffage_generateur_n1_installation_n1',
 'type_energie_n1',
 'emission_ges_eclairage',
 'type_energie_n2',
 'code_postal_ban',
 'emission_ges_ecs',
 'conso_5_usages_ef_energie_n2',
 'conso_5_usages_ef',
 'conso_5_usages_ef_energie_n1',
 'code_insee_ban',
 'deperditions_planchers_bas',
 'conso_5_usages_ep',
 'date_fin_validite_dpe',
 'deperditions_enveloppe',
 'code_region_ban',
 'volume_stockage_generateur_n1_ecs_n1',
 'surface_chauffee_installation_chauffage_n1',
 'version_dpe',
 'besoin_ecs',
 'coordonnee_cartographique_x_ban',
 'type_generateur_chauffage_principal',
 'type_energie_principale_ecs',
 'apport_solaire_saison_chauffe',
 'adresse_ban',
 'nombre_appartement',
 'deperditions_renouvellement_air',
 '_rand',
 'surface_habitable_desservie_par_installation_ecs_n1',
 'production_electricite_pv_kwhep_par_an',
 'type_installation_chauffage',
 'nombre_niveau_logement',
 'surface_habitable_logement',
 'cout_ecs',
 'type_installation_ecs_n1',
 'emission_ges_5_usages_energie_n1',
 'emission_ges_5_usages_energie_n2',
 'apport_interne_saison_froide',
 'emission_ges_5_usages_par_m2',
 'description_generateur_chauffage_n1_installation_n1',
 'qualite_isolation_plancher_haut_comble_perdu',
 'apport_interne_saison_chauffe',
 'apport_solaire_saison_froide',
 'type_generateur_n1_installation_n1',
 'nombre_logements_desservis_par_installation_ecs_n1',
 'complement_adresse_logement',
 'cout_auxiliaires',
 'type_emetteur_installation_chauffage_n1',
 'besoin_chauffage',
 'configuration_installation_ecs_n1',
 'description_installation_ecs_n1',
 'classe_inertie_batiment',
 'deperditions_ponts_thermiques',
 'type_generateur_chauffage_principal_ecs',
 'emission_ges_refroidissement',
 'hauteur_sous_plafond',
 'conso_chauffage_ef',
 'nom_commune_ban',
 'annee_construction',
 '_geopoint',
 'date_visite_diagnostiqueur',
 'type_batiment',
 'periode_construction',
 'type_installation_ecs',
 'conso_ecs_ep',
 'conso_ecs_ef',
 'emission_ges_5_usages',
 'date_derniere_modification_dpe',
 'etiquette_ges',
 'identifiant_ban',
 'deperditions_baies_vitrees',
 'type_energie_generateur_n1_ecs_n1',
 'ubat_w_par_m2_k',
 'numero_etage_appartement',
 'nom_commune_brut',
 'conso_ef_installation_ecs_n1',
 'etiquette_dpe',
 'description_generateur_n1_ecs_n1',
 'code_departement_ban',
 'type_installation_chauffage_n1',
 'methode_application_dpe',
 'adresse_brut',
 'cout_total_5_usages',
 'categorie_enr',
 'conso_refroidissement_ef',
 'conso_eclairage_ef',
 'deperditions_planchers_hauts',
 'zone_climatique',
 'conso_ef_generateur_n1_ecs_n1',
 'emission_ges_ecs_energie_n1',
 'emission_ges_ecs_energie_n2',
 'cout_refroidissement',
 'conso_chauffage_ep',
 'conso_eclairage_ep',
 'usage_generateur_n1_installation_n1',
 'nom_rue_ban',
 'qualite_isolation_murs',
 'type_installation_solaire_n1',
 'classe_altitude',
 'conso_refroidissement_ep',
 'type_energie_principale_chauffage',
 'numero_dpe',
 '_i',
 'besoin_refroidissement',
 'emission_ges_chauffage_energie_n2',
 'emission_ges_chauffage_energie_n1',
 'cout_chauffage_energie_n2',
 'deperditions_portes',
 'cout_chauffage_energie_n1',
 'coordonnee_cartographique_y_ban',
 'type_energie_generateur_n1_installation_n1',
 'code_postal_brut',
 'emission_ges_auxiliaires',
 'usage_generateur_n1_ecs_n1',
 '_score',
 '_id',
 'presence_brasseur_air',
 'isolation_toiture',
 'protection_solaire_exterieure',
 'logement_traversant',
 'indicateur_confort_ete',
 'inertie_lourde',
 'configuration_installation_chauffage_n2',
 'conso_chauffage_generateur_n1_installation_n2',
 'conso_chauffage_installation_chauffage_n2',
 'description_installation_chauffage_n2',
 'surface_chauffee_installation_chauffage_n2',
 'type_generateur_n1_installation_n2',
 'type_emetteur_installation_chauffage_n2',
 'description_generateur_chauffage_n1_installation_n2',
 'numero_dpe_remplace',
 'type_energie_climatisation',
 'surface_climatisee',
 'type_generateur_froid',
 'conso_refroidissement_annuel',
 'type_installation_chauffage_n2',
 'periode_installation_generateur_froid',
 'description_generateur_froid',
 'usage_generateur_n1_installation_n2',
 'type_energie_generateur_n1_installation_n2',
 'qualite_isolation_plancher_haut_comble_amenage',
 'qualite_isolation_plancher_haut_toit_terrasse',
 'nom_residence',
 'nombre_niveau_immeuble',
 'appartement_non_visite',
 'numero_dpe_immeuble_associe',
 'numero_immatriculation_copropriete',
 'systeme_production_electricite_origine_renouvelable',
 'presence_production_pv',
 'surface_ventilee',
 'type_ventilation',
 'date_installation_generateur_n1_ecs_n1',
 'description_generateur_chauffage_n2_installation_n1',
 'usage_generateur_n2_installation_n1',
 'type_generateur_n2_installation_n1',
 'type_energie_generateur_n2_installation_n1',
 'production_ecs_solaire_installation_n1',
 'facteur_couverture_solaire_n1',
 'conso_chauffage_generateur_n2_installation_n1',
 'complement_adresse_batiment',
 'surface_tertiaire_immeuble',
 'position_logement_dans_immeuble',
 'typologie_logement',
 'cop_generateur_n1_ecs_n1',
 'conso_ecs_ef_energie_n3',
 'cout_ecs_energie_n3',
 'conso_chauffage_ef_energie_n3',
 'cout_total_5_usages_energie_n3',
 'type_energie_n3',
 'conso_5_usages_ef_energie_n3',
 'emission_ges_5_usages_energie_n3',
 'emission_ges_ecs_energie_n3',
 'emission_ges_chauffage_energie_n3',
 'cout_chauffage_energie_n3',
 'electricite_pv_autoconsommee',
 'type_generateur_n2_ecs_n1',
 'volume_stockage_generateur_n2_ecs_n1',
 'date_installation_generateur_n2_ecs_n1',
 'usage_generateur_n2_ecs_n1',
 'conso_ef_generateur_n2_ecs_n1',
 'type_energie_generateur_n2_ecs_n1',
 'description_generateur_chauffage_n2_installation_n2',
 'usage_generateur_n2_installation_n2',
 'type_generateur_n2_installation_n2',
 'type_energie_generateur_n2_installation_n2',
 'conso_chauffage_generateur_n2_installation_n2',
 'surface_totale_capteurs_pv',
 'nombre_module',
 'facteur_couverture_solaire_installation_chauffage_n1',
 'facteur_couverture_solaire_saisi_n1',
 'facteur_couverture_solaire_saisi_installation_chauffage_n1',
 'provenance_id_rnb',
 'id_rnb',
 'description_generateur_n2_ecs_n1',
 'numero_rpls_logement']